from .base_infer import BaseInfer
from .build_infer import build_infer
from .multi_level_inference import Multilevel_inference
from .single_level_inference import Singlevel_inference
from .pixel_patch_inference import Pixel_patch_inference